### ISSUE TITLE
Squash PRs

### ISSUE THREAD

**Issue by ChristianMurphy** [Team-Delta/GitMyCurriculum#235]
use git squash to merge multiple commits for a single feature into one commit.
having dozens of commits for a single feature is excessive.

https://github.com/visionmedia/git-extras#git-squash-src-branch-msg

**Comment by bammons** [comment]
Reasons not to squash:
http://mikegerwitz.com/papers/git-horror-story.html

tl;dr
We can no longer follow the history of that feature/bugfix in order to learn how it was developed or see alternative solutions that were attempted but later replaced. (Cited from Mike Gerwitz's A Git Horror Story.)
It renders git bisect useless. If we find a bug in the software that was introduced by a single patch consisting of 300 squashed commits, we are left to dig through the code and debug ourselves, rather than having Git possibly figure out the problem for us. (Cited from Mike Gerwitz's A Git Horror Story.)

**Comment by ChristianMurphy** [comment]
squash using rebase can be selectively applied to history,
for example if a person were to forget to lint check their code before committing and committed several times to pass the lint checker (no functional code,
or were adding a single line of code at a time,
it could be required to squash those useless commits into one.

that would avoid the problem of merging heavily functional code.

**Comment by ChristianMurphy** [comment]
also when you do read the article,
that is for large feature branches of 100+ functional commits 1000+ loc,
not 5 functional commits and 40 loc.

**Comment by bammons** [comment]
Point being, that you don't even need to think about squashing when there is so little commits in the project.
